---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: payment
   labels:
      app: python
      project: roboshop
      service: payment
      env: dev
spec:
   replicas: 1
   selector:
      matchLabels:
         app: python
         project: roboshop
         service: payment
         env: dev
   template:
      metadata:
         labels:
            app: python
            project: roboshop
            service: payment
            env: dev
      spec:
         serviceAccountName: payment
         containers:
            - name: shipping
              image: hemanthtadikonda/payment:1.0.0
              ports:
                 - containerPort: 8080
              envFrom:
                 -  configMapRef:
                       name: payment-config
              resources:
                 requests:
                    memory: "500Mi"
                    cpu: "250m"
                 limits:
                    memory: "500Mi"
                    cpu: "250m"
              livenessProbe:
                 httpGet:
                    path: /health
                    port: 8080
                 initialDelaySeconds: 10
                 periodSeconds: 5
              readinessProbe:
                 httpGet:
                    path: /health
                    port: 8080
                 initialDelaySeconds: 10
                 periodSeconds: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: payment
---
apiVersion: v1
kind: Service
metadata:
   name: payment
spec:
   selector:
      app: python
      project: roboshop
      service: payment
      env: dev
   ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: payment-config
data:
   CART_HOST: 'cart'
   USER_HOST: 'user'
   AMPQ_HOST: 'rabbitmq'
---
